2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_setup.py:_flush():76] Configure stats pid to 96575
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'CNN Hyperparameter Tuning on MNIST', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': 'iq6jgcma', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-hvric81z/config-iq6jgcma.yaml', 'sweep_id': 'hvric81z'}
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231023_003436-iq6jgcma/logs/debug.log
2023-10-23 00:34:36,645 INFO    Thread-85 (_run_job):96575 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231023_003436-iq6jgcma/logs/debug-internal.log
2023-10-23 00:34:36,646 INFO    Thread-85 (_run_job):96575 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fa1a753be80>
2023-10-23 00:34:36,646 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():568] calling init triggers
2023-10-23 00:34:36,646 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():575] wandb.init called with sweep_config: {'batch_size': 64, 'dropout_rate': 0.5, 'epochs': 3, 'kernel_size': 3, 'learning_rate': 0.001, 'stride': 1}
config: {}
2023-10-23 00:34:36,646 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():618] starting backend
2023-10-23 00:34:36,646 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():622] setting up manager
2023-10-23 00:34:36,653 INFO    Thread-85 (_run_job):96575 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-23 00:34:36,654 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():628] backend started and connected
2023-10-23 00:34:36,666 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_config_callback():1324] config_cb None None {'batch_size': 64, 'dropout_rate': 0.5, 'epochs': 3, 'kernel_size': 3, 'learning_rate': 0.001, 'stride': 1}
2023-10-23 00:34:36,667 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-23 00:34:36,667 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-23 00:34:36,667 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():720] updated telemetry
2023-10-23 00:34:36,671 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-23 00:34:37,481 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_on_init():2220] communicating current version
2023-10-23 00:34:38,131 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_on_init():2229] got version response 
2023-10-23 00:34:38,131 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():804] starting run threads in backend
2023-10-23 00:34:38,165 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_console_start():2199] atexit reg
2023-10-23 00:34:38,166 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-23 00:34:38,166 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-23 00:34:38,166 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-23 00:34:38,168 INFO    Thread-85 (_run_job):96575 [wandb_init.py:init():845] run started, returning control to user process
2023-10-23 00:34:38,889 INFO    MainThread:96575 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-23 00:34:38,890 INFO    MainThread:96575 [wandb_init.py:_pause_backend():438] pausing backend
2023-10-23 00:35:47,408 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_finish():1934] finishing run mourya/CNN Hyperparameter Tuning on MNIST/iq6jgcma
2023-10-23 00:35:47,408 INFO    Thread-85 (_run_job):96575 [jupyter.py:save_history():445] not saving jupyter history
2023-10-23 00:35:47,408 INFO    Thread-85 (_run_job):96575 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-23 00:35:47,408 INFO    Thread-85 (_run_job):96575 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-23 00:35:47,408 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 1
2023-10-23 00:35:47,408 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_restore():2151] restore
2023-10-23 00:35:47,408 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_restore():2157] restore done
2023-10-23 00:35:47,409 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_restore():2151] restore
2023-10-23 00:35:47,409 INFO    Thread-85 (_run_job):96575 [wandb_run.py:_restore():2157] restore done
2023-10-23 00:35:48,411 ERROR   Thread-85 (_run_job):96575 [wandb_run.py:_atexit_cleanup():2189] Problem finishing run
Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 298, in _run_job
    self._function()
  File "/tmp/ipykernel_96575/507819091.py", line 93, in train
    print(validation_accuracy)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 640, in write
    self._old_write(data)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 648, in write
    self._schedule_flush()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 545, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 251, in schedule
    self._event_pipe.send(b"")
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2177, in _atexit_cleanup
    self._on_finish()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2412, in _on_finish
    self._footer_exit_status_info(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3397, in _footer_exit_status_info
    printer.display(f'{" ".join(info)}')
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 68, in display
    self._display(text, level=level, default_text=default_text)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 247, in _display
    self._display_fn_mapping(level)(text)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py", line 81, in display_html
    return display(HTML(html))
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/IPython/core/display_functions.py", line 305, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/IPython/core/display_functions.py", line 93, in publish_display_data
    display_pub.publish(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 102, in publish
    self._flush_streams()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 65, in _flush_streams
    sys.stdout.flush()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 559, in flush
    self.pub_thread.schedule(self._flush)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 251, in schedule
    self._event_pipe.send(b"")
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
