2023-10-12 13:31:44,577 INFO    MainThread:57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:31:44,577 INFO    MainThread:57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:31:44,577 INFO    MainThread:57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:31:44,577 INFO    MainThread:57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:31:44,577 INFO    MainThread:57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-12 13:31:44,577 INFO    MainThread:57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:31:44,578 INFO    MainThread:57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133144-2rk7falw/logs/debug.log
2023-10-12 13:31:44,578 INFO    MainThread:57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133144-2rk7falw/logs/debug-internal.log
2023-10-12 13:31:44,578 INFO    MainThread:57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:31:44,578 INFO    MainThread:57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2023-10-12 13:31:44,578 INFO    MainThread:57895 [wandb_init.py:init():593] re-initializing run, found existing run on stack: 929uvfuf
2023-10-12 13:31:44,579 INFO    MainThread:57895 [wandb_run.py:_finish():1934] finishing run mourya/MLP Classification on WineQT.csv/929uvfuf
2023-10-12 13:31:44,579 INFO    MainThread:57895 [jupyter.py:save_history():445] not saving jupyter history
2023-10-12 13:31:44,579 INFO    MainThread:57895 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-12 13:31:44,579 INFO    MainThread:57895 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-12 13:31:44,579 INFO    MainThread:57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:31:44,579 INFO    MainThread:57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:31:44,579 INFO    MainThread:57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:31:56,730 INFO    MainThread:57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:31:56,731 INFO    MainThread:57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:31:56,742 INFO    MainThread:57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:31:56,969 INFO    MainThread:57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:31:56,969 INFO    MainThread:57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:31:56,973 INFO    MainThread:57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:31:56,973 INFO    MainThread:57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:31:56,983 INFO    MainThread:57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:31:57,017 INFO    MainThread:57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:31:57,037 INFO    MainThread:57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:31:58,563 INFO    MainThread:57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:31:58,732 INFO    MainThread:57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:31:58,732 INFO    MainThread:57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:31:58,818 INFO    MainThread:57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:31:58,818 INFO    MainThread:57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:31:58,818 INFO    MainThread:57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:31:58,818 INFO    MainThread:57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:31:58,818 INFO    MainThread:57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:32:17,951 INFO    MainThread:57895 [pyagent.py:run():314] Starting sweep agent: entity=None, project=None, count=None
2023-10-12 13:32:32,591 WARNING MsgRouterThr:57895 [router.py:message_loop():77] message_loop has been closed
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'sweep_id': '3gxp58f5', 'run_id': '2j23w257', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-2j23w257.yaml'}
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133234-2j23w257/logs/debug.log
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133234-2j23w257/logs/debug-internal.log
2023-10-12 13:32:34,729 INFO    Thread-10 (_run_job):57895 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1ccaaf5ed0>
2023-10-12 13:32:34,730 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:32:34,730 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'sigmoid', 'optimizer': 'SGD'}
config: {}
2023-10-12 13:32:34,730 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:32:34,730 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:32:34,733 INFO    Thread-10 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:32:34,734 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:32:34,745 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'sigmoid', 'optimizer': 'SGD'}
2023-10-12 13:32:34,745 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:32:34,769 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:32:34,771 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:32:35,580 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:32:35,704 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:32:35,704 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:32:35,789 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:32:35,790 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:32:35,790 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:32:35,790 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:32:35,791 INFO    Thread-10 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:32:35,951 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/2j23w257
2023-10-12 13:32:35,951 INFO    Thread-10 (_run_job):57895 [jupyter.py:save_history():445] not saving jupyter history
2023-10-12 13:32:35,951 INFO    Thread-10 (_run_job):57895 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-12 13:32:35,951 INFO    Thread-10 (_run_job):57895 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-12 13:32:35,951 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:32:35,951 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:32:35,951 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:32:41,875 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:32:41,876 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:32:41,884 INFO    Thread-10 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:32:48,363 INFO    Thread-13 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:32:48,363 INFO    Thread-13 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:32:48,363 INFO    Thread-13 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:32:48,363 INFO    Thread-13 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:32:48,363 INFO    Thread-13 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': 'r05o5plc', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-r05o5plc.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133248-r05o5plc/logs/debug.log
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133248-r05o5plc/logs/debug-internal.log
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1cc93d3100>
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'sigmoid', 'optimizer': 'Batch'}
config: {}
2023-10-12 13:32:48,364 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:32:48,365 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:32:48,368 INFO    Thread-13 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:32:48,368 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:32:48,379 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'sigmoid', 'optimizer': 'Batch'}
2023-10-12 13:32:48,379 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:32:48,401 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:32:48,404 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:32:49,197 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:32:49,317 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:32:49,318 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:32:49,388 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:32:49,389 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:32:49,389 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:32:49,389 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:32:49,389 INFO    Thread-13 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:32:50,126 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/r05o5plc
2023-10-12 13:32:50,127 INFO    Thread-13 (_run_job):57895 [jupyter.py:save_history():445] not saving jupyter history
2023-10-12 13:32:50,127 INFO    Thread-13 (_run_job):57895 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-12 13:32:50,127 INFO    Thread-13 (_run_job):57895 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-12 13:32:50,127 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:32:50,128 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:32:50,128 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:32:56,214 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:32:56,214 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:32:56,223 INFO    Thread-13 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:33:12,939 INFO    Thread-16 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:33:12,939 INFO    Thread-16 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:33:12,939 INFO    Thread-16 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:33:12,940 INFO    Thread-16 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:33:12,940 INFO    Thread-16 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': '8wshvwi4', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-8wshvwi4.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:33:12,940 INFO    Thread-16 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:33:12,940 INFO    Thread-16 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:33:12,940 INFO    Thread-16 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133312-8wshvwi4/logs/debug.log
2023-10-12 13:33:12,940 INFO    Thread-16 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133312-8wshvwi4/logs/debug-internal.log
2023-10-12 13:33:12,940 INFO    Thread-16 (_run_job):57895 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1cc93f02b0>
2023-10-12 13:33:12,941 INFO    Thread-16 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:33:12,941 INFO    Thread-16 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'sigmoid', 'optimizer': 'MiniBatch'}
config: {}
2023-10-12 13:33:12,941 INFO    Thread-16 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:33:12,941 INFO    Thread-16 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:33:12,949 INFO    Thread-16 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:33:12,950 INFO    Thread-16 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:33:12,960 INFO    Thread-16 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'sigmoid', 'optimizer': 'MiniBatch'}
2023-10-12 13:33:12,960 INFO    Thread-16 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:33:12,963 INFO    Thread-16 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:33:12,966 INFO    Thread-16 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:33:31,162 INFO    Thread-17 (wrapped_target):57895 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f1cca5d0f40>: Failed to resolve 'api.wandb.ai' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1cca5d0f40>: Failed to resolve 'api.wandb.ai' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1cca5d0f40>: Failed to resolve 'api.wandb.ai' ([Errno -2] Name or service not known)"))
2023-10-12 13:34:15,946 INFO    Thread-9 (_heartbeat):57895 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f1cca5b2a40>: Failed to resolve 'api.wandb.ai' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1cca5b2a40>: Failed to resolve 'api.wandb.ai' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1cca5b2a40>: Failed to resolve 'api.wandb.ai' ([Errno -2] Name or service not known)"))
2023-10-12 13:34:43,048 ERROR   Thread-16 (_run_job):57895 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-12 13:34:45,052 ERROR   Thread-16 (_run_job):57895 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/ubuntulsa/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-12 13:34:45,053 ERROR   MainThread:57895 [pyagent.py:_run_jobs_from_queue():226] Run 8wshvwi4 errored: CommError('Run initialization has timed out after 90.0 sec. \nPlease refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-')
2023-10-12 13:34:56,265 WARNING MsgRouterThr:57895 [router.py:message_loop():77] message_loop has been closed
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': '7n1h5ju4', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-7n1h5ju4.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:34:58,344 INFO    Thread-19 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133458-7n1h5ju4/logs/debug.log
2023-10-12 13:34:58,345 INFO    Thread-19 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133458-7n1h5ju4/logs/debug-internal.log
2023-10-12 13:34:58,345 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:34:58,345 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'tanh', 'optimizer': 'SGD'}
config: {}
2023-10-12 13:34:58,345 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:34:58,345 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:34:58,348 INFO    Thread-19 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:34:58,349 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:34:58,356 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'tanh', 'optimizer': 'SGD'}
2023-10-12 13:34:58,357 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:34:58,360 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:34:58,363 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:34:59,085 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:34:59,647 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:34:59,647 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:34:59,693 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:34:59,693 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:34:59,693 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:34:59,693 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:34:59,694 INFO    Thread-19 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:34:59,828 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/7n1h5ju4
2023-10-12 13:34:59,828 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:34:59,828 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:34:59,828 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:35:05,678 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:35:05,678 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:35:05,681 INFO    Thread-19 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': 'l1a9ls2c', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-l1a9ls2c.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133512-l1a9ls2c/logs/debug.log
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133512-l1a9ls2c/logs/debug-internal.log
2023-10-12 13:35:12,020 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:35:12,021 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'tanh', 'optimizer': 'Batch'}
config: {}
2023-10-12 13:35:12,021 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:35:12,021 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:35:12,024 INFO    Thread-22 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:35:12,025 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:35:12,034 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'tanh', 'optimizer': 'Batch'}
2023-10-12 13:35:12,034 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:35:12,038 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:35:12,041 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:35:12,756 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:35:12,868 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:35:12,869 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:35:12,913 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:35:12,913 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:35:12,914 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:35:12,914 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:35:12,914 INFO    Thread-22 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:35:13,489 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/l1a9ls2c
2023-10-12 13:35:13,489 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:35:13,489 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:35:13,489 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:35:18,611 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:35:18,611 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:35:18,614 INFO    Thread-22 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:35:22,723 INFO    Thread-25 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:35:22,723 INFO    Thread-25 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:35:22,724 INFO    Thread-25 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:35:22,724 INFO    Thread-25 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:35:22,724 INFO    Thread-25 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': 'qn365bha', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-qn365bha.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:35:22,724 INFO    Thread-25 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:35:22,724 INFO    Thread-25 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:35:22,724 INFO    Thread-25 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133522-qn365bha/logs/debug.log
2023-10-12 13:35:22,724 INFO    Thread-25 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133522-qn365bha/logs/debug-internal.log
2023-10-12 13:35:22,725 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:35:22,725 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'tanh', 'optimizer': 'MiniBatch'}
config: {}
2023-10-12 13:35:22,725 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:35:22,725 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:35:22,730 INFO    Thread-25 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:35:22,730 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:35:22,740 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'tanh', 'optimizer': 'MiniBatch'}
2023-10-12 13:35:22,740 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:35:22,744 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:35:22,747 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:35:23,457 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:35:23,569 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:35:23,569 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:35:23,649 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:35:23,650 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:35:23,650 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:35:23,650 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:35:23,650 INFO    Thread-25 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:35:28,507 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/qn365bha
2023-10-12 13:35:28,507 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:35:28,507 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:35:28,507 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:35:34,720 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:35:34,720 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:35:34,726 INFO    Thread-25 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:35:39,020 INFO    Thread-28 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': 'rm81iuxf', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-rm81iuxf.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133539-rm81iuxf/logs/debug.log
2023-10-12 13:35:39,021 INFO    Thread-28 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133539-rm81iuxf/logs/debug-internal.log
2023-10-12 13:35:39,022 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:35:39,022 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'relu', 'optimizer': 'SGD'}
config: {}
2023-10-12 13:35:39,022 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:35:39,022 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:35:39,026 INFO    Thread-28 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:35:39,026 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:35:39,036 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'relu', 'optimizer': 'SGD'}
2023-10-12 13:35:39,037 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:35:39,040 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:35:39,042 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:35:39,736 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:35:39,855 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:35:39,856 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:35:39,962 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:35:39,962 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:35:39,962 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:35:39,962 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:35:39,963 INFO    Thread-28 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:35:40,105 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/rm81iuxf
2023-10-12 13:35:40,105 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:35:40,105 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:35:40,105 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:35:45,340 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:35:45,340 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:35:45,344 INFO    Thread-28 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:35:49,679 INFO    Thread-31 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:35:49,679 INFO    Thread-31 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:35:49,679 INFO    Thread-31 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:35:49,679 INFO    Thread-31 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:35:49,679 INFO    Thread-31 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': 'yhys0e4c', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-yhys0e4c.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:35:49,680 INFO    Thread-31 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:35:49,680 INFO    Thread-31 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:35:49,680 INFO    Thread-31 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133549-yhys0e4c/logs/debug.log
2023-10-12 13:35:49,680 INFO    Thread-31 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133549-yhys0e4c/logs/debug-internal.log
2023-10-12 13:35:49,680 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:35:49,681 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'relu', 'optimizer': 'Batch'}
config: {}
2023-10-12 13:35:49,681 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:35:49,681 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:35:49,688 INFO    Thread-31 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:35:49,689 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:35:49,701 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'relu', 'optimizer': 'Batch'}
2023-10-12 13:35:49,701 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:35:49,704 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:35:49,706 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:35:50,413 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:35:50,526 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:35:50,526 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:35:50,624 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:35:50,625 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:35:50,625 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:35:50,625 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:35:50,626 INFO    Thread-31 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:35:51,361 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/yhys0e4c
2023-10-12 13:35:51,361 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:35:51,361 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:35:51,361 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:35:55,404 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:35:55,405 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:35:55,414 INFO    Thread-31 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-10-12 13:36:00,539 INFO    Thread-34 (_run_job):57895 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-12 13:36:00,539 INFO    Thread-34 (_run_job):57895 [wandb_setup.py:_flush():76] Configure stats pid to 57895
2023-10-12 13:36:00,540 INFO    Thread-34 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/.config/wandb/settings
2023-10-12 13:36:00,540 INFO    Thread-34 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/settings
2023-10-12 13:36:00,540 INFO    Thread-34 (_run_job):57895 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'your_project_name', 'entity': 'mourya', 'root_dir': '/home/ubuntulsa/Sem5/SMAI/Assignment 3', 'run_id': 'lusf56k2', 'sweep_param_path': '/home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/sweep-3gxp58f5/config-lusf56k2.yaml', 'sweep_id': '3gxp58f5'}
2023-10-12 13:36:00,540 INFO    Thread-34 (_run_job):57895 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-12 13:36:00,540 INFO    Thread-34 (_run_job):57895 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-12 13:36:00,541 INFO    Thread-34 (_run_job):57895 [wandb_init.py:_log_setup():528] Logging user logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133600-lusf56k2/logs/debug.log
2023-10-12 13:36:00,541 INFO    Thread-34 (_run_job):57895 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ubuntulsa/Sem5/SMAI/Assignment 3/wandb/run-20231012_133600-lusf56k2/logs/debug-internal.log
2023-10-12 13:36:00,541 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():568] calling init triggers
2023-10-12 13:36:00,542 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation': 'relu', 'optimizer': 'MiniBatch'}
config: {}
2023-10-12 13:36:00,542 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():618] starting backend
2023-10-12 13:36:00,542 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():622] setting up manager
2023-10-12 13:36:00,550 INFO    Thread-34 (_run_job):57895 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-12 13:36:00,551 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():628] backend started and connected
2023-10-12 13:36:00,560 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_config_callback():1324] config_cb None None {'activation': 'relu', 'optimizer': 'MiniBatch'}
2023-10-12 13:36:00,560 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-12 13:36:00,563 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():720] updated telemetry
2023-10-12 13:36:00,566 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-12 13:36:01,251 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_on_init():2220] communicating current version
2023-10-12 13:36:01,354 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-12 13:36:01,354 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():804] starting run threads in backend
2023-10-12 13:36:01,403 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_console_start():2199] atexit reg
2023-10-12 13:36:01,404 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-12 13:36:01,404 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-12 13:36:01,404 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-12 13:36:01,404 INFO    Thread-34 (_run_job):57895 [wandb_init.py:init():845] run started, returning control to user process
2023-10-12 13:36:06,677 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_finish():1934] finishing run mourya/your_project_name/lusf56k2
2023-10-12 13:36:06,678 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-12 13:36:06,678 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_restore():2151] restore
2023-10-12 13:36:06,678 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_restore():2157] restore done
2023-10-12 13:36:13,360 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-10-12 13:36:13,360 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-10-12 13:36:13,366 INFO    Thread-34 (_run_job):57895 [wandb_run.py:_footer_sync_info():3513] logging synced files
